on:
  push:
    branches:
      - main
    paths:
      - Specs/Quint/**
  pull_request:
    paths:
      - Specs/Quint/**

name: Quint

jobs:
  quint-typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Specs/Quint
      strategy:
        fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install -g @informalsystems/quint
      - run: npx @informalsystems/quint typecheck consensus.qnt
      - run: npx @informalsystems/quint typecheck voteBookkeeper.qnt

