name: Rust

on:
  push:
    branches: master
    paths:
      - Code/**
  pull_request:
    paths:
      - Code/**

permissions:
  checks: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install cargo-nextest
        uses: taiki-e/install-action@cargo-hack
      - name: Build code
        working-directory: Code
        run: cargo nextest run --workspace --all-features --no-run
      - name: Run tests
        working-directory: Code
        run: cargo nextest run --workspace --all-features

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Run clippy
        uses: auguwu/clippy-action@1.3.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          args: --manifest-path Code/Cargo.toml
 
  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Check formatting
        uses: actions-rust-lang/rustfmt@v1
        with:
          manifest-path: Code/Cargo.toml
